### ISSUE TITLE
Tesseract model cannot be loaded in your machine.

### ISSUE THREAD

**Issue by Castllee** [blueaxis/Poricom#40]
I've got Poricom v0.3.1 on my machine, and when I tried to use the new version it said that the Tesseract model can't be loaded on your machine, use Manga OCR instead.  [img](https://imgur.com/a/3j9bQEA)

**Comment by Kromtar** [comment]
+1

**Comment by blueaxis** [comment]
I added this popup error to handle #29. As mentioned in the message, you are getting the error since Tesseract model cannot be loaded. Have you tried using the MangaOCR model?

**Comment by macacoverde** [comment]
I've been having this same issue sometimes, even though I'm using MangaOCR the whole time. And it also kind of messes up the log file, it repeats the previous text when you capture after getting  the error message.

**Comment by user18081972** [comment]
[error.webm](https://user-images.githubusercontent.com/124319511/226144377-3d6811ed-2b63-4dd6-9103-7584e1b6f040.webm)
I think there is something wrong with the error detection, it says "you are now using MangaOCR" then I try to do OCR and it says "Tesserect could not be loaded"

**Comment by blueaxis** [comment]
This will be fixed in the next release.

As a workaround, try to wait a few seconds before you release the mouse button. Even if this error is fixed, what you're currently doing (instantly releasing the mouse button) wouldn't work @user18081972.
