### ISSUE TITLE
Linux installer/executable for Poricom

### ISSUE THREAD

**Issue by yupm** [blueaxis/Poricom#41]
As user I would like a .deb, .rpm or .appimage installer for Poricom on Linux.
Will work on it if no one picks this up.

**Comment by blueaxis** [comment]
No idea if the pyinstaller file will work on Linux since I only tested it on Windows. You can try running it though. Just post the build here so I can test it on a VM

**Comment by yupm** [comment]
Tested on Ubuntu baremetal and Debian based VM.
Package is large mainly due to OCR torch module libraries.
