### ISSUE TITLE
How can I copy the OCR result into the clipboard?

### ISSUE THREAD

**Issue by WekFer** [blueaxis/Poricom#43]
I can see the result displayed on the gray blackground as the tutorial goes, but I can't copy anything
Run on the windows 10, 64-bit operating system
I can't fix it myself. But I run the Manga OCR successfully, which can also fulfill my need.

**Comment by blueaxis** [comment]
For future readers, or in case you haven't resolved this, Poricom automatically copies the result to your clipboard. So you don't need to do any configuration for that.

Or were you having a different problem?

**Comment by WekFer** [comment]
My clipboard doesn't get the text result. 
There's another problem. It recognize the text at the first time and display it at the top left corner. But later it doesn't work, displays nothing and reminds that "Tesseract model cannot be loaded in your machine, please use the MangaOcr instead". But it seems like it has a trouble in downloading the MangaOCR model. I'm not sure if the downloading failure is a problem of my internet connection. I've encountered a similar problem while downloading the MangaOCR model directly and I've found a method to solve it, which however doesn't work in this case. 
Maybe it would be better if Poricom can set the model by choosing the MangaOCR model file manually? I'm not sure. Now I'm using the MangaOCR directly in command line with the downloaded model file and it works well.

**Comment by blueaxis** [comment]
One of your errors should be fixed in #44 

> I've encountered a similar problem while downloading the MangaOCR model directly and I've found a method to solve it

May I know how you've managed to load the model locally? How did you download and name the files? And where did you place it?

**Comment by WekFer** [comment]
https://github.com/kha-white/manga-ocr/issues/25
I found that my model is in the %UserProfile%.cache\huggingface\hub\models--kha-white--manga-ocr-base\snapshots\a-long-string folder called pytorch_model.bin (maybe). I copy the whole "models--kha-white--manga-ocr-base" folder to an other place, and run manga_ocr with a flag -p the\path\to\the\pytorch_model.bin, and it works.

**Comment by blueaxis** [comment]
Got it, thanks. Offline loading should be available in the latest release now.
