### ISSUE TITLE
Crashing while zooming in or out

### ISSUE THREAD

**Issue by nekosaurus** [blueaxis/Poricom#49]
Exactly as the title says. I tried to see if my setting "Fit to height" was the problem, but it also crashes on "Fit to width" and "Fit to screen."

On another note, instead of having the "You are now using MangaOCR" popup appear every time on launch, I think it would be better if there was a icon of some sort at the top that would switch between green/red or whatever indicating if MangaOCR is being used or not. Anyway, thanks for the hard work!

**Comment by blueaxis** [comment]
What's the size of the image you're viewing? I can't seem to replicate the issue even on large files. Also can you provide a demo video?

**Comment by nekosaurus** [comment]
https://imgur.com/a/8xspXj9

Hopefully the imgur link is legible. The images aren't really that big. 1131 x 1608 resolution and they're usually around 1 MB each. Previous versions were fine so I'm not sure why this release is messing things up.

**Comment by blueaxis** [comment]
Oh I was trying to replicate using the scroll shortcut. I think I know what's causing this, will release a fix later
