### ISSUE TITLE
No option to "copy to clipboard" (ENHANCEMENT)

### ISSUE THREAD

**Issue by ONEsuzuki** [blueaxis/Poricom#71]
Really strange why would I want to hustle around a TXT, it's built mainly for Japanese and most learners use yomichan dictionary because it pulls text from clip-board. Seems like a missed opportunity the app looks and feels so far very nice though.
I'm sure this would be possible look forward to you're thoughts.

**Comment by seth-js** [comment]
I'm not sure what you're asking about. It already copies text to the clipboard by default for me.

**Comment by ONEsuzuki** [comment]
> I'm not sure what you're asking about. It already copies text to the clipboard by default for me.

Just didn't see it listed in the app anywhere, or the GitHub page as a feature. Thanks for the reply sorry for wasting you're time.
